#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/eShopOrder/eShop.Order.API/eShop.Order.API.csproj", "src/eShopOrder/eShop.Order.API/"]
RUN dotnet restore "src/eShopOrder/eShop.Order.API/eShop.Order.API.csproj"
COPY . .
WORKDIR "/src/src/eShopOrder/eShop.Order.API"
RUN dotnet build "./eShop.Order.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./eShop.Order.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "eShop.Order.API.dll"]