version: '3.8'

services:
  mongodb:
    image: mongo:7.0.14
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - eshop-network

  rabbitmq:
    image: rabbitmq:3.12.14-management
    restart: always
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - eshop-network

  eshop.order.api:
    build:
      context: .
      dockerfile: src/eShopOrder/eShop.Order.API/Dockerfile
    container_name: eshoporderapi
    restart: always
    depends_on:
      - mongodb
      - rabbitmq

    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTP_PORTS=8080
      - MongoDBOrdersCollectionName=${MONGODB_COLLETION}
      - MongoDBConnectionString=${MONGODB_URI}
      - MongoDBDatabaseName=${MONGODB_DATABASE}
      - RabbitMQHostName=${RABBITMQ_HOSTNAME}
      - RabbitMQUserName=${RABBITMQ_USERNAME}
      - RabbitMQPassword=${RABBITMQ_PASSWORD}
      - RabbitMQQueueName=${RABBITMQ_ORDERQUEUENAME}
      - RabbitMQPaymentStatusQueueName=${RABBITMQ_PAYMENTSTATUSQUEUENAME}
    networks:
      - eshop-network

  eshop.order.worker:
    build:
      context: .
      dockerfile: src/eShopOrder/eShop.Order.Worker/Dockerfile
    container_name: eshoporderworker
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - OrderApiBaseUrl=${ORDER_API_BASE_URL}
      - RabbitMQHostName=${RABBITMQ_HOSTNAME}
      - RabbitMQUserName=${RABBITMQ_USERNAME}
      - RabbitMQPassword=${RABBITMQ_PASSWORD}
      - RabbitMQQueueName=${RABBITMQ_PAYMENTSTATUSQUEUENAME}
    depends_on:
      - rabbitmq
    networks:
      - eshop-network

  eshop.payment.worker:
    build:
      context: .
      dockerfile: src/eShopPayment/eShop.Payment.Worker/Dockerfile
    container_name: eshoppaymentworker
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RabbitMQHostName=${RABBITMQ_HOSTNAME}
      - RabbitMQUserName=${RABBITMQ_USERNAME}
      - RabbitMQPassword=${RABBITMQ_PASSWORD}
      - RabbitMQQueueName=${RABBITMQ_ORDERQUEUENAME}
      - RabbitMQPaymentStatusQueueName=${RABBITMQ_PAYMENTSTATUSQUEUENAME}
    depends_on:
      - rabbitmq
    networks:
      - eshop-network

volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/mongo
  
networks:
  eshop-network:
    driver: bridge
